# Generated by Django 3.1.3 on 2020-12-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Código postal')),
                ('date', models.CharField(max_length=20, unique=True, verbose_name='Fecha Nacimiento')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('address', models.CharField(max_length=80, unique=True, verbose_name='Direccion')),
                ('lastname', models.CharField(max_length=80, unique=True, verbose_name='Apellido')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Número de Teléfono')),
            ],
        ),
    ]
