# Generated by Django 3.1.3 on 2020-12-15 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50, unique=True, verbose_name='Número Aula')),
                ('capacity', models.CharField(max_length=3, unique=True, verbose_name='Capacidad')),
                ('floor', models.CharField(max_length=20, unique=True, verbose_name='Edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50, unique=True, verbose_name='ID Materia')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre Materia')),
                ('hour', models.CharField(max_length=20, unique=True, verbose_name='Horas')),
                ('credit', models.CharField(max_length=20, unique=True, verbose_name='Créditos')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
