# Generated by Django 3.1.3 on 2020-12-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classroom_matter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=50, unique=True, verbose_name='ID Clase')),
                ('hour', models.CharField(max_length=20, unique=True, verbose_name='Hora Clase')),
                ('Classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('Matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.matter')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
